'use client';

import { useState, useMemo } from 'react';
import { X, Copy, Check, FileText, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Version, Task } from '@/lib/types';

interface ChangelogModalProps {
    version: Version;
    tasks: Task[];
    onClose: () => void;
    onRelease?: () => void;
}

type ChangelogFormat = 'markdown' | 'plain' | 'html';

export default function ChangelogModal({ version, tasks, onClose, onRelease }: ChangelogModalProps) {
    const [format, setFormat] = useState<ChangelogFormat>('markdown');
    const [copied, setCopied] = useState(false);
    const [includeDate, setIncludeDate] = useState(true);
    const [groupByPriority, setGroupByPriority] = useState(false);

    const completedTasks = useMemo(() => tasks.filter(t => t.isDone), [tasks]);
    const pendingTasks = useMemo(() => tasks.filter(t => !t.isDone), [tasks]);

    const generateChangelog = useMemo(() => {
        const date = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        let content = '';

        if (format === 'markdown') {
            content = `## ${version.name}${includeDate ? ` - ${date}` : ''}\n\n`;

            if (groupByPriority) {
                const priorities = ['urgent', 'high', 'medium', 'low', 'none'] as const;
                const priorityLabels: Record<string, string> = {
                    urgent: '🔴 Critical',
                    high: '🟠 High Priority',
                    medium: '🟡 Medium Priority',
                    low: '🟢 Low Priority',
                    none: '⚪ Other'
                };

                for (const priority of priorities) {
                    const priorityTasks = completedTasks.filter(t => (t.priority || 'none') === priority);
                    if (priorityTasks.length > 0) {
                        content += `### ${priorityLabels[priority]}\n\n`;
                        priorityTasks.forEach(task => {
                            content += `- ${task.content}\n`;
                            if (task.description) {
                                content += `  > ${task.description.split('\n')[0]}\n`;
                            }
                        });
                        content += '\n';
                    }
                }
            } else {
                if (completedTasks.length > 0) {
                    content += `### ✅ Completed\n\n`;
                    completedTasks.forEach(task => {
                        content += `- ${task.content}\n`;
                        if (task.description) {
                            content += `  > ${task.description.split('\n')[0]}\n`;
                        }
                    });
                    content += '\n';
                }
            }

            if (pendingTasks.length > 0) {
                content += `### ⏳ Known Issues / Remaining\n\n`;
                pendingTasks.forEach(task => {
                    content += `- ${task.content}\n`;
                });
                content += '\n';
            }

            content += `---\n*Generated by My Version Manager*\n`;

        } else if (format === 'plain') {
            content = `${version.name}${includeDate ? ` - ${date}` : ''}\n`;
            content += '='.repeat(version.name.length + (includeDate ? date.length + 3 : 0)) + '\n\n';

            if (completedTasks.length > 0) {
                content += `COMPLETED:\n`;
                completedTasks.forEach(task => {
                    content += `  • ${task.content}\n`;
                });
                content += '\n';
            }

            if (pendingTasks.length > 0) {
                content += `PENDING:\n`;
                pendingTasks.forEach(task => {
                    content += `  • ${task.content}\n`;
                });
            }

        } else if (format === 'html') {
            content = `<h2>${version.name}${includeDate ? ` <small>${date}</small>` : ''}</h2>\n`;

            if (completedTasks.length > 0) {
                content += `<h3>✅ Completed</h3>\n<ul>\n`;
                completedTasks.forEach(task => {
                    content += `  <li>${task.content}</li>\n`;
                });
                content += `</ul>\n`;
            }

            if (pendingTasks.length > 0) {
                content += `<h3>⏳ Pending</h3>\n<ul>\n`;
                pendingTasks.forEach(task => {
                    content += `  <li>${task.content}</li>\n`;
                });
                content += `</ul>\n`;
            }
        }

        return content;
    }, [version, completedTasks, pendingTasks, format, includeDate, groupByPriority]);

    const handleCopy = async () => {
        await navigator.clipboard.writeText(generateChangelog);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const extension = format === 'html' ? 'html' : format === 'markdown' ? 'md' : 'txt';
        const blob = new Blob([generateChangelog], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `changelog-${version.name.replace(/\s+/g, '-').toLowerCase()}.${extension}`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={onClose}>
            <div
                className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-slate-50 to-white">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center">
                            <FileText className="w-5 h-5 text-emerald-600" />
                        </div>
                        <div>
                            <h2 className="font-bold text-slate-800 text-lg">Changelog Generator</h2>
                            <p className="text-sm text-slate-500">{version.name} • {completedTasks.length} completed, {pendingTasks.length} pending</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Options Bar */}
                <div className="px-6 py-3 bg-slate-50 border-b border-slate-100 flex flex-wrap items-center gap-4">
                    {/* Format Selector */}
                    <div className="flex items-center gap-2">
                        <span className="text-xs font-medium text-slate-500 uppercase">Format:</span>
                        <div className="flex bg-white border border-slate-200 rounded-lg p-0.5">
                            {(['markdown', 'plain', 'html'] as const).map(f => (
                                <button
                                    key={f}
                                    onClick={() => setFormat(f)}
                                    className={`px-3 py-1 text-xs font-medium rounded-md transition-all ${format === f ? 'bg-emerald-500 text-white shadow-sm' : 'text-slate-600 hover:text-slate-800'}`}
                                >
                                    {f.charAt(0).toUpperCase() + f.slice(1)}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Toggles */}
                    <label className="flex items-center gap-2 cursor-pointer">
                        <input
                            type="checkbox"
                            checked={includeDate}
                            onChange={e => setIncludeDate(e.target.checked)}
                            className="w-4 h-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"
                        />
                        <span className="text-xs text-slate-600">Include date</span>
                    </label>

                    <label className="flex items-center gap-2 cursor-pointer">
                        <input
                            type="checkbox"
                            checked={groupByPriority}
                            onChange={e => setGroupByPriority(e.target.checked)}
                            className="w-4 h-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"
                        />
                        <span className="text-xs text-slate-600">Group by priority</span>
                    </label>
                </div>

                {/* Preview */}
                <div className="flex-1 overflow-y-auto p-6">
                    <div className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-2">Preview</div>

                    {format === 'markdown' ? (
                        <div className="prose prose-sm prose-slate max-w-none bg-slate-50 p-4 rounded-xl border border-slate-100">
                            <ReactMarkdown>{generateChangelog}</ReactMarkdown>
                        </div>
                    ) : (
                        <pre className="bg-slate-900 text-slate-100 p-4 rounded-xl text-sm overflow-x-auto font-mono">
                            {generateChangelog}
                        </pre>
                    )}
                </div>

                {/* Footer Actions */}
                {/* Footer Actions */}
                <div className="px-6 py-4 border-t border-slate-100 bg-slate-50/50 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <div className="text-xs text-slate-400">
                            {generateChangelog.length} characters
                        </div>
                        {version.isActive && onRelease && (
                            <button
                                onClick={() => {
                                    if (confirm('Are you sure you want to release this version? It will be marked as inactive.')) {
                                        onRelease();
                                    }
                                }}
                                className="text-xs font-semibold text-blue-600 hover:text-blue-700 hover:underline"
                            >
                                🚀 Release Version
                            </button>
                        )}
                    </div>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={handleDownload}
                            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded-lg transition-colors"
                        >
                            <Download className="w-4 h-4" />
                            Download
                        </button>
                        <button
                            onClick={handleCopy}
                            className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-all ${copied ? 'bg-emerald-100 text-emerald-700' : 'bg-emerald-600 text-white hover:bg-emerald-700'}`}
                        >
                            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                            {copied ? 'Copied!' : 'Copy to Clipboard'}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
